articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # create
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),

    # comment
    # create
    path('<int:id>/comments/create/', views.comment_create, name='comment_create'),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    # articles/ 로 시작되면 모두 articles.urls에서 실행해줘
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    
# 모델을 새로 만들었으면 번역본 만드는 코드도 다시 실행

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm): # 입력폼 생성 클래스
    class Meta(): # 폼의 설정을 담당하는 클래스
        model = Article # Article이 가진 필드를 기준으로
        fields = '__all__' # 모든 필드를 이 폼에서 입력할게

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('content',) # 튜플로 써야함

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, CommentForm
from .models import Article

# Create your views here.

# 사용자가 요청하면(접속) 쓸 수 있는 빈 종이를 마련한다(GET)
# 사용자가 작성한 종이를 제출한다(POST)
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)  # 사용자의 데이터를 담은 제출 서류
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm() # 빈 종이
    context = {
        'form': form,
        }
    return render(request, 'create.html', context)

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'detail.html', context)


def update(request, id):
    # edit
    article = Article.objects.get(id=id) # 수정할 글 가져오기
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article) # 앞은 덮어쓸 새정보, 뒤는 이전 정보
        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }

    return render(request, 'update.html', context)


def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('articles:index')


def comment_create(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            # 저장하지 말고 대기해, 댓글 달 게시물의 index값이 안들어왔기 때문
            # comment.article = article 여기 밑에까지 설명필요..
            # comment.save()
        pass
    else:
        return redirect('articles:detail', id=id)
    
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<h3>{{article.title}}</h3>
<p>{{article.content}}</p>
<p>{{article.created_at}}</p>
<p>{{article.updated_at}}</p>
<a href="{% url 'articles:index' %}">home</a>
<a href="{% url 'articles:update' article.id %}">edit</a>
<a href="{% url 'articles:delete' article.id %}">delete</a>
<hr>
<form action="{% url 'articles:comment_create' article.id}" method="POST">
    <!-- 요기 articles:comment_create는 urls.py의 name에서 불러옴 -->
     {% csrf_token %}
     {{form}}
     <!-- form이 detail함수 안에 정의가 되어 있어야 불러와 쓸 수 있음 -->
    <input type="submit">
    <!-- submit을 눌러야 위의 POST가 작동됨(기입된 정보를 가지고 제출!) -->
</form>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
    {% for article in articles %}
    <h3>{{article.title}}</h3>
    <p>{{article.content}}</p>
    <a href="{% url 'articles:detail' article.id %}">detail</a>
    {% endfor %}
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
    <!-- detail에서 update를 하려고 edit을 눌러 글 수정 후 게시하면 -->
     <!-- 현재 위치에서 재실행됨 -->
    {% csrf_token%}
    {{form}}
    <input type="submit">

</form>
{% endblock %}